SELECT DISTINCT dbo.TLG_EMP_CURRENT.EMPLOYEE_ID, dbo.TLG_EMP_CURRENT.EMPLOYEE_NAME, TEAMLEAD_NAME, STATUS_NAME, EMAIL_ADDRESS
from dbo.TLG_EMP_CURRENT
WHERE dbo.TLG_EMP_CURRENT.HOME_TEAM_NAME = 'CLIENTSYS'