SELECT DISTINCT dbo.V_SLG_Epic_Contacts.EmpName as PerfTS
						INTO #TempTable
						FROM dbo.V_SLG_Epic_Contacts 
							INNER JOIN dbo.TLG_EMP_CURRENT on dbo.V_SLG_Epic_Contacts.EmpName = dbo.TLG_EMP_CURRENT.EMPLOYEE_NAME
						WHERE 
							dbo.TLG_EMP_CURRENT.HOME_TEAM_NAME = 'PERFORMANCE'

SELECT DISTINCT dbo.SLG_BASIC_OVERTIME.SEQUENCE_NUMBER AS SLG#, guru.CustomersVisibleInGuru.Name, dbo.SLG_BASIC_OVERTIME.CONTACT_TITLE as Title,
					dbo.SLG_BASIC_OVERTIME.LOG_STATUS_C AS Status, dbo.SLG_BASIC_OVERTIME.LAST_UPDATE_INSTANT, dbo.SLG_BASIC_OVERTIME.CREATION_INSTANT, 
					dbo.SLG_BASIC_OVERTIME.PRIORITY_C,

FROM guru.CustomersVisibleInGuru
		INNER JOIN dbo.SLG_BASIC_OVERTIME on guru.CustomersVisibleInGuru.CUSTOMER_NUMBER = dbo.SLG_BASIC_OVERTIME.CUSTOMER_NUMBER
		INNER JOIN dbo.TLG_EMP_CURRENT on dbo.SLG_BASIC_OVERTIME.BATON_HOLDER = dbo.TLG_EMP_CURRENT.EMPLOYEE_ID

WHERE (dbo.SLG_BASIC_OVERTIME.BATON_HOLDER = '10512' AND dbo.SLG_BASIC_OVERTIME.CONTACT_TYPE = '50' AND dbo.SLG_BASIC_OVERTIME.LOG_STATUS_C != '300')