SELECT DISTINCT dbo.V_SLG_Epic_Contacts.EmpName AS PerfTS, dbo.V_SLG_Epic_Contacts.CUSTOMER_NAME

FROM dbo.V_SLG_Epic_Contacts 
	INNER JOIN dbo.TLG_EMP_CURRENT on dbo.V_SLG_Epic_Contacts.EmpName = dbo.TLG_EMP_CURRENT.EMPLOYEE_NAME

WHERE  dbo.TLG_EMP_CURRENT.HOME_TEAM_NAME = 'PERFORMANCE'
	--AND dbo.V_SLG_Epic_Contacts.EmpName IN (SELECT DISTINCT dbo.TLG_EMP_CURRENT.EMPLOYEE_NAME FROM dbo.TLG_EMP_CURRENT WHERE dbo.TLG_EMP_CURRENT.HOME_TEAM_NAME = 'PERFORMANCE')

